function createimage(cdata1, Parent1)
%CREATEIMAGE(CDATA1, PARENT1)
%  CDATA1:  image cdata
%  PARENT1:  image parent

%  Auto-generated by MATLAB on 13-Oct-2016 13:11:40

% Create image
image(cdata1,'Parent',Parent1);

